# Generated by Django 4.1.7 on 2023-03-07 15:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='departements')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medcin',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('IDMedcin', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medcins/avatar/')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('anniversaire', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('h', 'Homme'), ('f', 'Femme')], default='h', help_text='Select genre', max_length=1)),
                ('views', models.IntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('twitter', models.CharField(blank=True, help_text='Twitter', max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook', max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram', max_length=200, null=True)),
                ('linkdin', models.CharField(blank=True, help_text='Linkdin', max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, help_text='Linkdin', max_length=200, null=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_departement', to='core.departement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialisations',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='specialites')),
            ],
            options={
                'verbose_name': 'Specialite',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='SpecialisationMedcin',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_SpecialisationMedcin', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medcin',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_specialite', to='core.specialite'),
        ),
        migrations.AddField(
            model_name='medcin',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('titre', models.CharField(blank=True, help_text="Le libelle de l'cole", max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medcins/galerie/')),
                ('description', models.TextField(blank=True, null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_galerie', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('poste', models.CharField(blank=True, help_text='Le libelle du poste occupé', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, help_text='Date de debut de la formation', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de la formation', null=True)),
                ('clinique', models.ForeignKey(blank=True, help_text='Selectionner la clinique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_clinique_experience', to='core.clinique')),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_clinique_experience', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('formation', models.CharField(blank=True, help_text='Le libelle de la formation', max_length=255, null=True)),
                ('ecole', models.CharField(blank=True, help_text="Le libelle de l'cole", max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, help_text='Date de debut de la formation', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de la formation', null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_education', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('joursDisponibilite', models.CharField(blank=True, help_text='Les jours de disponibilité', max_length=255, null=True)),
                ('tempsDisponibilite', models.CharField(blank=True, help_text='Temps de disponibilité', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Ce champ est ptionnel', null=True)),
                ('heure_debut_lundi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_lundi', models.TimeField(blank=True, help_text='Heure de fin de fin fin', null=True)),
                ('heure_debut_mardi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_mardi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_mercredi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_mercredi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_jeudi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_jeudi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_vendredi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_vendredi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_samedi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_samedi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_dimanche', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_dimanche', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_disponibilite', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('titre', models.CharField(blank=True, help_text='Le libelle du Certificat', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, help_text='Date', null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_Certificat', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
