# Generated by Django 4.1.7 on 2023-03-09 16:49

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
import djmoney.models.validators
import phonenumber_field.modelfields
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='departements')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medcin',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('addresse', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('h', 'Homme'), ('f', 'Femme')], default='h', help_text='Select genre', max_length=1)),
                ('statut_matrimonial', models.CharField(blank=True, choices=[('célibataire', 'Célibataire'), ('mariée', 'Marié/Mariée'), ('veuve', 'Veuf/Veuve'), ('divorcée', 'Divorcé/Divorcée')], default='célibataire', help_text='statut matrimonial', max_length=100)),
                ('civilite', models.CharField(blank=True, choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], default='Monsieur', help_text='select civilité', max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Twitter', max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook', max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram', max_length=200, null=True)),
                ('linkdin', models.CharField(blank=True, help_text='Linkdin', max_length=200, null=True)),
                ('IDMedcin', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medcins/avatars/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='medcins/signatures/')),
                ('views', models.IntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_departement', to='core.departement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('addresse', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('h', 'Homme'), ('f', 'Femme')], default='h', help_text='Select genre', max_length=1)),
                ('statut_matrimonial', models.CharField(blank=True, choices=[('célibataire', 'Célibataire'), ('mariée', 'Marié/Mariée'), ('veuve', 'Veuf/Veuve'), ('divorcée', 'Divorcé/Divorcée')], default='célibataire', help_text='statut matrimonial', max_length=100)),
                ('civilite', models.CharField(blank=True, choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], default='Monsieur', help_text='select civilité', max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Twitter', max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook', max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram', max_length=200, null=True)),
                ('linkdin', models.CharField(blank=True, help_text='Linkdin', max_length=200, null=True)),
                ('IDPatient', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/avatar/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='patients/signatures/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('libelle', django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nationnalite', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_pays', to='core.pays')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialisations',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='specialites')),
            ],
            options={
                'verbose_name': 'Specialite',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Type_Piece',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_region', to='core.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialisationMedcin',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_SpecialisationMedcin', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('date', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('etat', models.CharField(blank=True, choices=[('en attente', 'En attente'), ('en cours', 'En cours'), ('terminé', 'Terminé')], default='en attente', help_text='Select etat', max_length=50)),
                ('prix_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default=None, editable=False, max_length=3)),
                ('prix', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(10), djmoney.models.validators.MaxMoneyValidator(1500)])),
                ('medcin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_rendezvous', to='core.medcin')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_patient_rendezvous', to='core.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('date_etablissement', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_expiration', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('lieu_etablissemnt', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('numero_piece', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('type_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_type_piece', to='core.type_piece')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_p_piece', to='core.piece'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_id_profession', to='core.profession'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_personne_ville', to='core.ville'),
        ),
        migrations.AddField(
            model_name='medcin',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_piece', to='core.piece'),
        ),
        migrations.AddField(
            model_name='medcin',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_specialite', to='core.specialite'),
        ),
        migrations.AddField(
            model_name='medcin',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='medcin',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_ville', to='core.ville'),
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('titre', models.CharField(blank=True, help_text="Le libelle de l'cole", max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medcins/galerie/')),
                ('description', models.TextField(blank=True, null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_galerie', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('poste', models.CharField(blank=True, help_text='Le libelle du poste occupé', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, help_text='Date de debut de la formation', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de la formation', null=True)),
                ('clinique', models.ForeignKey(blank=True, help_text='Selectionner la clinique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_clinique_experience', to='core.clinique')),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_clinique_experience', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('formation', models.CharField(blank=True, help_text='Le libelle de la formation', max_length=255, null=True)),
                ('ecole', models.CharField(blank=True, help_text="Le libelle de l'cole", max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, help_text='Date de debut de la formation', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de la formation', null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_education', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('joursDisponibilite', models.CharField(blank=True, help_text='Les jours de disponibilité', max_length=255, null=True)),
                ('tempsDisponibilite', models.CharField(blank=True, help_text='Temps de disponibilité', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Ce champ est ptionnel', null=True)),
                ('heure_debut_lundi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_lundi', models.TimeField(blank=True, help_text='Heure de fin de fin fin', null=True)),
                ('heure_debut_mardi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_mardi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_mercredi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_mercredi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_jeudi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_jeudi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_vendredi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_vendredi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_samedi', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_samedi', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('heure_debut_dimanche', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin_dimanche', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_disponibilite', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('titre', models.CharField(blank=True, help_text='Le libelle du Certificat', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, help_text='Date', null=True)),
                ('medcin', models.ForeignKey(blank=True, help_text='Selectionner le medcin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_Certificat', to='core.medcin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
