# Generated by Django 4.1.7 on 2023-03-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pays_profession_region_ville_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='region',
        ),
        migrations.AddField(
            model_name='region',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_pays', to='core.pays'),
        ),
        migrations.AddField(
            model_name='ville',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_region', to='core.region'),
        ),
    ]
