# Generated by Django 4.1.7 on 2023-03-09 10:28

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_age_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Piece',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='medcin',
            old_name='adresse',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='medcin',
            old_name='anniversaire',
            new_name='code_postal',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='adresse',
            new_name='addresse',
        ),
        migrations.RemoveField(
            model_name='medcin',
            name='youtube',
        ),
        migrations.AddField(
            model_name='medcin',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medcin',
            name='civilite',
            field=models.CharField(blank=True, choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], default='Monsieur', help_text='select civilité', max_length=100),
        ),
        migrations.AddField(
            model_name='medcin',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medcin',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medcin',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='medcins/signatures/'),
        ),
        migrations.AddField(
            model_name='medcin',
            name='statut_matrimonial',
            field=models.CharField(blank=True, choices=[('célibataire', 'Célibataire'), ('mariée', 'Marié/Mariée'), ('veuve', 'Veuf/Veuve'), ('divorcée', 'Divorcé/Divorcée')], default='célibataire', help_text='statut matrimonial', max_length=100),
        ),
        migrations.AddField(
            model_name='medcin',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_ville', to='core.ville'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='civilite',
            field=models.CharField(blank=True, choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], default='Monsieur', help_text='select civilité', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='patients/signatures/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut_matrimonial',
            field=models.CharField(blank=True, choices=[('célibataire', 'Célibataire'), ('mariée', 'Marié/Mariée'), ('veuve', 'Veuf/Veuve'), ('divorcée', 'Divorcé/Divorcée')], default='célibataire', help_text='statut matrimonial', max_length=100),
        ),
        migrations.AddField(
            model_name='pays',
            name='nationnalite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medcin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medcins/avatars/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_id_profession', to='core.profession'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_personne_ville', to='core.ville'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('date_etablissement', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_expiration', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('lieu_etablissemnt', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('numero_piece', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('id_type_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_type_piece', to='core.type_piece')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medcin',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_piece', to='core.piece'),
        ),
        migrations.AddField(
            model_name='patient',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_p_piece', to='core.piece'),
        ),
    ]
