# Generated by Django 4.1.7 on 2023-03-10 14:18

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, help_text='active ou desactive')),
                ('created', models.DateField(auto_now_add=True, help_text='Create date', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date')),
                ('date', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, help_text='Heure de debut', null=True)),
                ('heure_fin', models.TimeField(blank=True, help_text='Heure de fin de fin', null=True)),
                ('etat', models.CharField(blank=True, choices=[('en attente', 'En attente'), ('en cours', 'En cours'), ('terminé', 'Terminé')], default='en attente', help_text='Select etat', max_length=50)),
                ('prix_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default=None, editable=False, max_length=3)),
                ('prix', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(10), djmoney.models.validators.MaxMoneyValidator(1500)])),
            ],
        ),
    ]
