# Generated by Django 4.1.7 on 2023-03-10 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_medcin', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('midle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/avatar/')),
                ('about', models.TextField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('session_token', models.CharField(default=0, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('addresse', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('h', 'Homme'), ('f', 'Femme')], default='h', help_text='Select genre', max_length=1)),
                ('statut_matrimonial', models.CharField(blank=True, choices=[('célibataire', 'Célibataire'), ('mariée', 'Marié/Mariée'), ('veuve', 'Veuf/Veuve'), ('divorcée', 'Divorcé/Divorcée')], default='célibataire', help_text='statut matrimonial', max_length=100)),
                ('civilite', models.CharField(blank=True, choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], default='Monsieur', help_text='select civilité', max_length=100)),
                ('twitter', models.CharField(blank=True, help_text='Twitter', max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook', max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram', max_length=200, null=True)),
                ('linkdin', models.CharField(blank=True, help_text='Linkdin', max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, help_text='Linkdin', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_piece', to='parametres.piece')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_medcin_ville', to='parametres.ville')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('IDPatient', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/profile/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='patients/signatures/')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_id_profession', to='parametres.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Medcin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('IDMedcin', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medcins/profile/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='medcins/signatures/')),
                ('views', models.IntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_departement', to='parametres.departement')),
                ('specialisation', models.ManyToManyField(blank=True, null=True, related_name='fk_specialisation', to='parametres.specialisations')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_specialite', to='parametres.specialite')),
            ],
        ),
    ]
